name: Linux Build

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run Tests
        run: |
          cargo test --release --target x86_64-unknown-linux-gnu
          cargo test --release --target i686-unknown-linux-gnu

      - name: Create folder release
        run: mkdir release

      - name: Build Linux Binary x64
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/cargo-workspace release/cargo-workspace-x64

      - name: Build Linux Binary x32
        run: |
          cargo build --release --target i686-unknown-linux-gnu
          cp target/i686-unknown-linux-gnu/release/cargo-workspace release/cargo-workspace-x32

      - name: Upload Linux Binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: release/*

      - name: Upload Linux Binary to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/cargo-workspace-x64
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}

      - name: Upload x32 Binary to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/cargo-workspace-x32
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}
