name: Linux Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run Tests
        run: |
          cargo test --release --target x86_64-unknown-linux-gnu
          cargo test --release --target i686-unknown-linux-gnu

      - name: Create folder release
        run: mkdir -p release

      - name: Build Linux Binary x64
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/cargo-workspace ./release/cargo-workspace-x64

      - name: Build Linux Binary x32
        run: |
          cargo build --release --target i686-unknown-linux-gnu
          cp target/i686-unknown-linux-gnu/release/cargo-workspace ./release/cargo-workspace-x32

      - name: Upload Linux Binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: release/*

      - name: Upload Linux Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/cargo-workspace-x64
          asset_name: cargo-workspace-x64
          asset_content_type: application/octet-stream

      - name: Upload x32 Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/cargo-workspace-x32
          asset_name: cargo-workspace-x32
          asset_content_type: application/octet-stream
