name: Windows Build

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run Tests
        run: |
          cargo test --release --target x86_64-pc-windows-msvc
          cargo test --release --target i686-pc-windows-msvc

      - name: Create folder release
        run: mkdir release

      - name: Build Windows Binary x64
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          copy target\x86_64-pc-windows-msvc\release\cargo-workspace.exe release\cargo-workspace-x64.exe

      - name: Build Windows Binary x32
        run: |
          cargo build --release --target i686-pc-windows-msvc
          copy target\i686-pc-windows-msvc\release\cargo-workspace.exe release\cargo-workspace-x32.exe

      - name: Upload Windows Binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: release/*

      - name: Debug Event
        run: echo "${{ toJson(github.event) }}"

      - name: Upload Windows Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/cargo-workspace-x64.exe
          asset_name: cargo-workspace-x64.exe
          asset_content_type: application/octet-stream

      - name: Upload x32 Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_WORKSPACE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/cargo-workspace-x32.exe
          asset_name: cargo-workspace-x32.exe
          asset_content_type: application/octet-stream
